question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Video streaming website YouTube was purchased in it&#039;"
                 "s entirety by Facebook for US$1.65 billion in stock.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "French is an official language in Canada.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                                       "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "The mitochondria is the powerhouse of the cell.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]}
    ]
